#!/bin/sh

# run from this dir
cd "$(dirname "$0")"

# ensure we have an editor
editor="${EDITOR:-$(cat .my-editor 2>/dev/null)}"
if test -z "$editor"
then
  echo "You need to provide your editor"
  echo "either set the environment variable EDITOR"
  echo "or create a file here named .my-editor"
  echo "whose body is the name of your editor"
  exit 1
fi

# find today's file
date="$(date "+%Y-%m-%d")"
file="source/outlines/$date.markdown"

# edito today's file
"$editor" "$file"
